server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/billboard
  user: billboard
  password: billboard_passwd